In [70]:
import pandas as pd

In [74]:
%cd /Users/mikemwanga/Documents/FG/Analysis/

/Users/mikemwanga/Documents/FG/Analysis

In [79]:
All = pd.read_excel('FG_Data.xls', sheet_name = 'All')

add = pd.read_excel('FG_Data.xls', sheet_name = 'Sheet1')

In [76]:
All.head()

,KEMRI_ID,Lane_ID,Serial_x,Genotype_x,G1_seq,length_x,Genotype_y,P8_Seq,Length,Genotype,...,length.1.1,Genotype_x.1.1,NSP3_Seq,Length.1,NSP4_Genotype,NSP4_Seq,length_y,Genotype_y.1.1,NSP5_Seq,length
0,95822,20719_78,20719_78/95822/G1,G1,aaggagtatttctaacatccacattatgtttgtattatccaactga...,764.0,P[8],cagaaaaaactcaaaatgtaactgtaaatccaggtccatttgctca...,1422.0,I1,...,528.0,T2,atggctagttcaattattaacacttcttttgaagccgcagtcgttg...,915.0,E2,atggaaaagcttaccgacctcaattacacattgagtgtaatcactc...,423.0,H3,atgtctctcagtattgacgtgacgagtcttccttctatttcttcta...,594.0
1,103390,20719_83b,20719_83b/103390/G1,G1,ttattatcgcaaatgtttcttacaaaagggtggccaacaggatcag...,681.0,NaN,NaN,0.0,NaN,...,954.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,106440,20668_86,20668_86/106440/G1,G1,cattatgtttgtataatccaactgaagcaagtactcaaatcagtga...,743.0,P[8],ccagcttctcactaattcatattcagtagatttatatgatgaaata...,2308.0,I1,...,954.0,T1,atggagtctactcagcagatggtaagctctattattaacacttctt...,933.0,E1,atggataagcttgccgacctcaactacacattgagtgtaatcactt...,528.0,H1,atgtctctcagcattgacgtaacaagtcttccctcaatttcttcta...,594.0
3,106454,20668_11,20668_11/106454/G1,G1,atgtatggtattgaatataccacaattctaatctttctgatatcaa...,981.0,P[8],cagcttctcactaattcatattcagtagatttatatgatgaaatag...,2307.0,I1,...,948.0,T1,atggagtctactcagcagatggtaagctctattattaacacttctt...,933.0,E1,aactacacattgagtgtaatcactttaatgaatgacacattacatt...,507.0,H1,atgtctctcagcattgacgtaacaagtcttccctcaatttcttcta...,594.0
4,106554,20719_87,20719_87/106554/G1,G1,atgtatggtattgaatataccacaattctaatctttctgatatcaa...,981.0,P[8],cagcttctcactaattcatattcagtagatttatatgatgaaatag...,2307.0,I1,...,948.0,T1,atggagtctactcagcagatggtaagctctattattaacacttctt...,933.0,E1,atggataagcttgccgacctcaactacacattgagtgtaatcactt...,528.0,H1,atgtctctcagcattgacgtaacaagtcttccctcaatttcttcta...,594.0

In [77]:
add.head()

,KEMRI_ID,age_mnths,Collection_date,Seq_Annotation,Period,date_admission,SeqID,VP7_GB_Acc_No,VP4_GB_Acc_No
0,95684,11,2009-12-31 00:00:00,RVA/Human-wt/KEN/KLF0274/2009/G1P[x],,,KEN/RVA/0274,MH402391,
1,95724,10,2010-01-01 00:00:00,RVA/Human-wt/KEN/KLF0275/2010/GxP[4],pre-vaccine,2009-12-31 00:00:00,KEN/RVA/0275,,MH402923
2,95739,2,2010-01-02 00:00:00,RVA/Human-wt/KEN/KLF0276/2010/G8P[x],pre-vaccine,2010-01-01 00:00:00,KEN/RVA/0276,MH402630,
3,95743,8,2010-01-02 00:00:00,RVA/Human-wt/KEN/KLF0277/2010/G1P[8],pre-vaccine,2010-01-02 00:00:00,KEN/RVA/0277,MH402179,MH403230
4,95808,10,2010-01-05 00:00:00,RVA/Human-wt/KEN/KLF0278/2010/G8P[4],pre-vaccine,2010-01-05 00:00:00,KEN/RVA/0278,MH402670,MH402807

In [80]:
#merge data

merged = pd.merge(All, add, on='KEMRI_ID', how='outer')

merged.head()

,KEMRI_ID,Lane_ID,Serial_x,Genotype_x,G1_seq,length_x,Genotype_y,P8_Seq,Length,Genotype,...,NSP5_Seq,length,age_mnths,Collection_date,Seq_Annotation,Period,date_admission,SeqID,VP7_GB_Acc_No,VP4_GB_Acc_No
0,95822,20719_78,20719_78/95822/G1,G1,aaggagtatttctaacatccacattatgtttgtattatccaactga...,764.0,P[8],cagaaaaaactcaaaatgtaactgtaaatccaggtccatttgctca...,1422.0,I1,...,atgtctctcagtattgacgtgacgagtcttccttctatttcttcta...,594.0,15,2010-01-05,RVA/Human-wt/KEN/KLF0279/2010/G29P[x],pre-vaccine,2010-01-05 00:00:00,KEN/RVA/0279,MH402528,
1,103390,20719_83b,20719_83b/103390/G1,G1,ttattatcgcaaatgtttcttacaaaagggtggccaacaggatcag...,681.0,NaN,NaN,0.0,NaN,...,NaN,NaN,17,2010-12-18,RVA/Human-wt/KEN/KLF0389/2010/G8P[x],pre-vaccine,2010-12-17 00:00:00,KEN/RVA/0389,MH402646,MN194352
2,106440,20668_86,20668_86/106440/G1,G1,cattatgtttgtataatccaactgaagcaagtactcaaatcagtga...,743.0,P[8],ccagcttctcactaattcatattcagtagatttatatgatgaaata...,2308.0,I1,...,atgtctctcagcattgacgtaacaagtcttccctcaatttcttcta...,594.0,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
3,106454,20668_11,20668_11/106454/G1,G1,atgtatggtattgaatataccacaattctaatctttctgatatcaa...,981.0,P[8],cagcttctcactaattcatattcagtagatttatatgatgaaatag...,2307.0,I1,...,atgtctctcagcattgacgtaacaagtcttccctcaatttcttcta...,594.0,11,2011-05-17,RVA/Human-wt/KEN/KLF0446/2011/G1P[8],pre-vaccine,2011-05-15 00:00:00,KEN/RVA/0446,MH402384,MH403463
4,106554,20719_87,20719_87/106554/G1,G1,atgtatggtattgaatataccacaattctaatctttctgatatcaa...,981.0,P[8],cagcttctcactaattcatattcagtagatttatatgatgaaatag...,2307.0,I1,...,atgtctctcagcattgacgtaacaagtcttccctcaatttcttcta...,594.0,7,2011-05-21,RVA/Human-wt/KEN/KLF0451/2011/G1P[8],pre-vaccine,2011-05-20 00:00:00,KEN/RVA/0451,MH402265,MH403436

In [59]:
merged.tail()

,Unnamed: 0,KEMRI_ID,Serial_x,G1_seq,Genotype_x,length_x,Serial_y,P8_Seq,Genotype_y,Serial_x.1,...,NSP4_Seq,length_y,Serial_x,Genotype_y.1.1,NSP5_Seq,length,Serial_y,Genotype,VP6_Seq,Length_y
1060,628,132140,132140/02Jul2015/VP7/G1P[8],atgtatggtattgaatataccacaattctaatctttctgatatcaa...,G1,981.0,132140/02-Jul-2015/VP4/G1P8,atggcttcgctcatttatagacagcttctcactaattcatattcag...,P[8],132140/02Jul2015/VP1/G1P[8],...,atggataagcttgccgaccttaactacacattgagtgtaatcactt...,528.0,RVA/Humanwt/KEN/132140/02Jul2015/NSP5_6/G1P[8],H1,atgtctctcagcattgacgtaacgagtcttccctcaatttcttcta...,594.0,RVA/Humanwt/KEN/132140/02Jul2015/VP6/G1P[8],I1,atggaggttctgtattcattgtcaaaaactctcaaagatgctaggg...,1194.0
1061,629,123792,20669_90b/123792/G1,cgaataatggactacattatatatagatttttgttaatttttgtag...,G1,585.0,20669_90b/123792/P8,actcgtaggaatgttaaaatatggtggaagaatatggacatttcat...,P[8],NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1062,630,117396,20669_4/117396/G1,atgtatggtattgaatataccacaattctaatctttctgatatcaa...,G1,981.0,20669_4/117396/P8,atggcttcgctcatttataggcagcttctcactaattcatattcag...,P[8],20669_4/117396/R1,...,acggataagcttgccgacctcaattacacattgagtgtaatcactt...,354.0,20669_4/117396/H1,H1,gtaacaagtcttccctcaatttcttctagtatctttaaaaatgaat...,576.0,20669_4/117396/I1,I1,gctagggataaaattgttgaaggtacattatattctaatgttagtg...,1155.0
1063,631,119055,20669_49/119055/G1,atgtatggtattgaatataccacaattctaatctttctgatatcaa...,G1,981.0,20669_49/119055/P8,tatagccagcttctcactaattcatattcagtagatttatatgatg...,P[8],20669_49/119055/R1,...,atggataagcttgccgacctcaactacacattgagtgtaatcactt...,528.0,20669_49/119055/H1,H1,atgtctctcagcattgacgtaacaagtcttccctcaatttcttcta...,594.0,20669_49/119055/I1,I1,atggaggttctatattcattgtcaaaaactcttaaagatgctaggg...,1194.0
1064,632,131661,NaN,NaN,NaN,NaN,NaN,NaN,NaN,131661/10Jun2015/VP1/G1P[8],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [81]:
merged.to_excel('FG_Merged_Data.xls')